### ISSUE TITLE
Unexpected token '<'

### ISSUE THREAD

**Issue by AlexChambers** [MonicaUnlimited/ClientEngagementAdmin2#1]
There is an error when the page loads which reads: "Unexpected token '<'".
<img width="1440" alt="screen shot 2017-08-24 at 10 39 07 am" src="https://user-images.githubusercontent.com/8173907/29680403-4ae713c6-88b9-11e7-8322-3a8d284ab032.png">

**Comment by MonicaUnlimited** [comment]
i'm a NEWB... :-(

**Comment by MonicaUnlimited** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/8810031-163907986_10-s1-v1.png?transparent=1&palette=1&width=246)
